/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PssoundMembership = {
  _id: string
  _type: 'pssoundMembership'
  _createdAt: string
  _updatedAt: string
  _rev: string
  collectiveName?: string
  isPolitical?: Array<string>
  otherPolitical?: string
  caribbeanOrAfro?: boolean
  qualifiedSoundEngineer?: 'yes' | 'no_commit'
  annualContribution?: string
  charterSigned?: boolean
  approved?: boolean
  startDate?: string
}

export type HighlightedBox = {
  _type: 'highlightedBox'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'h2' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & TextColor)
      | ({
          _key: string
        } & HighlightColor)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  useCustomBgColor?: boolean
  customBgColor?: string
  useCustomTextColor?: boolean
  customTextColor?: string
}

export type CallToAction = {
  _type: 'callToAction'
  heading?: string
  text?: string
  buttonText?: string
  link?: Link
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  openInNewTab?: boolean
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    post?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'post'
    }
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type ResourceTag = {
  _id: string
  _type: 'resourceTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type PssoundArchive = {
  _id: string
  _type: 'pssoundArchive'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  date?: string
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
}

export type ResourceSubmission = {
  _id: string
  _type: 'resourceSubmission'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  url?: string
  email?: string
  tags?: Array<string>
  description?: string
  approved?: boolean
  submittedAt?: string
}

export type ArchiveTag = {
  _id: string
  _type: 'archiveTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type ArchiveMedia = {
  _id: string
  _type: 'archiveMedia'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  category?: 'text' | 'video' | 'sound' | 'website'
  url?: string
  fileUrl?: string
  file?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  email?: string
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'resourceTag'
  }>
  approved?: boolean
  publishedAt?: string
}

export type PssoundCalendar = {
  _id: string
  _type: 'pssoundCalendar'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  startDate?: string
  endDate?: string
  notes?: string
  request?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'pssoundRequest'
  }
}

export type PssoundManual = {
  _id: string
  _type: 'pssoundManual'
  _createdAt: string
  _updatedAt: string
  _rev: string
  pdf?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
}

export type PssoundRequest = {
  _id: string
  _type: 'pssoundRequest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  collective?: string
  eventTitle?: string
  eventLink?: string
  eventLocation?: string
  eventDescription?: string
  isPolitical?: {
    feminist?: boolean
    queer?: boolean
    racial?: boolean
    disability?: boolean
    fundraiser?: string
    other?: string
  }
  marginalizedArtists?: Array<{
    name?: string
    link?: string
    _key: string
  }>
  wagePolicy?: string
  eventDate?: string
  pickupDate?: string
  returnDate?: string
  vehicleCert?: boolean
  teamCert?: boolean
  charterCert?: boolean
  membershipCert?: boolean
  status?: 'pending' | 'approved' | 'declined'
  approved?: boolean
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  date?: string
  location?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'eventTag'
  }>
  url?: string
}

export type WorkshopRegistration = {
  _id: string
  _type: 'workshopRegistration'
  _createdAt: string
  _updatedAt: string
  _rev: string
  workshop?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'workshop'
  }
  name?: string
  email?: string
  selectedDates?: Array<string>
  message?: string
  status?: 'pending' | 'approved' | 'rejected' | 'waitlisted'
  notes?: string
  registrationDate?: string
}

export type Workshop = {
  _id: string
  _type: 'workshop'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  dates?: Array<string>
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'workshopTag'
  }>
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal' | 'largeParagraph' | 'largeQuestion'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  totalSpots?: number
  availableSpots?: number
}

export type WorkshopTag = {
  _id: string
  _type: 'workshopTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type EventTag = {
  _id: string
  _type: 'eventTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
}

export type PsstSection = {
  _id: string
  _type: 'psstSection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title?: string
  slug?: Slug
  layout?: 'default' | 'guidelines'
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type PsstPage = {
  _id: string
  _type: 'psstPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  charter?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
  about?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
  legal?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal' | 'largeParagraph' | 'largeQuestion'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        linkType?: 'href' | 'page'
        href?: string
        page?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  heading?: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'artist'
  }
}

export type Artist = {
  _id: string
  _type: 'artist'
  _createdAt: string
  _updatedAt: string
  _rev: string
  artistName?: string
  slug?: Slug
  pronouns?:
    | 'he/him'
    | 'she/her'
    | 'they/them'
    | 'he/they'
    | 'she/they'
    | 'prefer_not_to_say'
    | 'other'
  customPronouns?: string
  email?: string
  categories?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'category'
  }>
  links?: Array<{
    url?: string
    platform?: string
    _key: string
  }>
  description?: string
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
  approved?: boolean
}

export type MembershipPage = {
  _id: string
  _type: 'membershipPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type PageSettings = {
  _id: string
  _type: 'pageSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
          | {
              linkType?: 'internal' | 'external'
              internalLink?: string
              href?: string
              openInNewTab?: boolean
              _type: 'link'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type Guidelines = {
  _id: string
  _type: 'guidelines'
  _createdAt: string
  _updatedAt: string
  _rev: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'h2' | 'normal' | 'largeParagraph' | 'largeQuestion'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & TextColor)
          | ({
              _key: string
            } & HighlightColor)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & HighlightedBox)
  >
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  soundcloudPlaylistUrl?: string
}

export type HighlightColor = {
  _type: 'highlightColor'
  label?: string
  value?: string
}

export type TextColor = {
  _type: 'textColor'
  label?: string
  value?: string
}

export type SimplerColor = {
  _type: 'simplerColor'
  label?: string
  value?: string
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message?: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | PssoundMembership
  | HighlightedBox
  | CallToAction
  | Link
  | InfoSection
  | BlockContent
  | ResourceTag
  | PssoundArchive
  | ResourceSubmission
  | ArchiveTag
  | ArchiveMedia
  | Resource
  | PssoundCalendar
  | PssoundManual
  | PssoundRequest
  | Event
  | WorkshopRegistration
  | Workshop
  | WorkshopTag
  | EventTag
  | Tag
  | Category
  | PsstSection
  | PsstPage
  | Homepage
  | Page
  | Post
  | Artist
  | MembershipPage
  | PageSettings
  | Guidelines
  | Settings
  | HighlightColor
  | TextColor
  | SimplerColor
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
