import {defineField, defineType} from 'sanity'

export const resource = defineType({
  name: 'resource',
  title: 'Resource',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'internal', title: 'Internal'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      group: 'content',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      group: 'content',
      type: 'text',
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      group: 'content',
      type: 'array',
      of: [{type: 'reference', to: {type: 'resourceCategory'}}],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'url',
      title: 'URL',
      group: 'content',
      type: 'url',
      description: 'External link to resource',
    }),
    defineField({
      name: 'fileUrl',
      title: 'File URL',
      group: 'content',
      type: 'url',
      description: 'Link to downloadable file',
    }),
    defineField({
      name: 'file',
      title: 'Upload File',
      group: 'content',
      type: 'file',
      description: 'Upload a file directly',
    }),
    defineField({
      name: 'image',
      title: 'Image',
      group: 'content',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      group: 'content',
      type: 'array',
      of: [{type: 'reference', to: {type: 'resourceTag'}}],
    }),
    defineField({
      name: 'approved',
      title: 'Approved',
      group: 'content',
      type: 'boolean',
      initialValue: false,
      description: 'Check to approve this resource and make it visible on the site.',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      group: 'content',
      type: 'datetime',
      description: 'Used for chronological sorting. Submitted resources get this when approved.',
    }),
    defineField({
      name: 'email',
      title: 'Submitter Email',
      group: 'internal',
      type: 'string',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'submissionSource',
      title: 'Submission source',
      group: 'internal',
      type: 'string',
      readOnly: true,
      hidden: ({document}) => !document?.submissionSource,
      description:
        'Set automatically for website submissions. Manually added resources stay blank.',
    }),
    defineField({
      name: 'category',
      title: 'Legacy category',
      group: 'internal',
      type: 'string',
      readOnly: true,
      hidden: ({document}) => !document?.category,
      description: 'Old fixed category value kept only as migration fallback.',
    }),
    defineField({
      name: 'submittedAt',
      title: 'Submitted at',
      group: 'internal',
      type: 'datetime',
      readOnly: true,
      hidden: ({document}) => !document?.submittedAt,
    }),
    defineField({
      name: 'confirmationEmailSentAt',
      title: 'Confirmation email sent at',
      group: 'internal',
      type: 'datetime',
      readOnly: true,
      hidden: ({document}) => !document?.confirmationEmailSentAt,
    }),
    defineField({
      name: 'approvalEmailSentAt',
      title: 'Approval email sent at',
      group: 'internal',
      type: 'datetime',
      readOnly: true,
      hidden: ({document}) => !document?.approvalEmailSentAt,
    }),
    defineField({
      name: 'emailDeliveryError',
      title: 'Email delivery error',
      group: 'internal',
      type: 'text',
      readOnly: true,
      hidden: ({document}) => !document?.emailDeliveryError,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'categories.0.title',
      media: 'image',
    },
  },
})
